module.exports = {
  BAD_PARAMETERS: 'BAD_PARAMETERS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  MISSING_AUTH_HEADER: 'MISSING_AUTH_HEADER',
  WRONG_AUTH_TYPE: 'WRONG_AUTH_TYPE',
  WRONG_ISSUER: 'WRONG_ISSUER',
  WRONG_AUDIENCE: 'WRONG_AUDIENCE',
  WRONG_SCOPE: 'WRONG_SCOPE',
};
